### ISSUE TITLE
Session Fixation

### ISSUE THREAD

**Issue by s-newman** [s-newman/skitter#6]

**Comment by ducphanduyagentp** [comment]
We generate a session ID everytime a user logins so I don't think we have this problem. I will just close this for now.
For reference: https://www.owasp.org/index.php/Session_fixation

**Comment by ducphanduyagentp** [comment]
We may have a bigger problem than I thought. This is from the Web Application Hacker's handbook

>  The application does not issue tokens to anonymous users, and a token is issued only following a successful login. However, if a user accesses the login function using an authenticated token and logs in using different credentials, no new token is issued. Instead, the user associated with the previously authenticated session is changed to the identity of the second user.
