### ISSUE TITLE
Password Brute-Forcing

### ISSUE THREAD

**Issue by s-newman** [s-newman/skitter#8]
Attackers should not be able to brute force a user's password.  We need to test for and guard against this kind of attack.

**Comment by ducphanduyagentp** [comment]
My tentative implementation for this will be as following:

- The authentication server keeps track of number of failed login attempts and put in into the database, so the database schema will likely to be changed when I implement this, probably just adding a new table.
- Implement 2 additional `/blockUser` and `/unblockUser` endpoints on the authentication server

**Comment by ducphanduyagentp** [comment]
Or even simpler, just use CAPTCHA.
